title: Your awesome title
email: joseph.r.stansfield@gmail.com
description: some stuff
baseurl: ""
url: "http://jstans12.github.io"
github_username:  JStans12

# build settings
markdown: kramdown
theme: minima
