title: "Joey Stansfield"
email: joseph.r.stansfield@gmail.com
description: ""
baseurl: ""
url: "http://jstans12.github.io"
github_username:  jstans12

markdown: kramdown
theme: minima

# gems
gems:
  - jekyll-gist
