title: "Hi, I'm Joey"
email: joseph.r.stansfield@gmail.com
description: ""
baseurl: ""
url: "http://jstans12.github.io"
github_username:  jstans12

# build settings
markdown: kramdown
theme: minima

# gems
gems:
  - jekyll-gist
