title: "Joey Stansfield"
email: joseph.r.stansfield@gmail.com
description: ""
baseurl: ""
url: "http://jstans12.github.io"
github_username:  jstans12
linkedin_username: joseph-stansfield-a546b973

markdown: kramdown

# gems
gems:
  - jekyll-gist
